name: Generate Docs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1

      - name: Build
        run: cargo build --release

      - name: Change directory and show files
        run: |
          cd /target/release/
          pwd
          tree

      - name: Mark executable
        run: chmod +x release_workflows.exe

      - name: Generate Docs
        run: ./release_workflows.exe --static-docs

      - name: Copy HTML files to GitHub Pages directory
        run: |
          mkdir -p docs
          cp -R ./*.html docs/

      - name: Commit and push changes to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout gh-pages
          git add docs/*
          git commit -m "Update docs"
          git push origin gh-pages
