name: Generate Docs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release


      - name: Mark executable
        run: |
          find . -type f -name "release_workflows" -exec chmod +x {} \;

      - name: Generate Docs
        run: |
          cd ./target/release/
          ./release_workflows --static-docs

      - name: Change directory and show files
        run: |
          cd ./target/release/
          ls

      - name: Copy HTML files to GitHub Pages directory
        run: |
          mkdir -p docs
          cp -R  ./target/release/*.html docs/

      - name: Commit and push changes to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout gh-pages
          git add docs/*
          git commit -m "Update docs"
          git push origin gh-pages
